name: Deploy English Site to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build with VitePress (English only)
        run: |
          npm run docs:build:en
          ls -la docs/.vitepress/
          ls -la docs/.vitepress/dist/ || echo "dist directory not found"

      - name: Create _site directory
        run: |
          mkdir -p _site
          if [ -d "docs/.vitepress/dist" ]; then
            cp -r docs/.vitepress/dist/* _site/
          else
            echo "Warning: dist directory not found, creating empty _site"
            mkdir -p _site
          fi
          ls -la _site/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4